[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.armv7-unknown-linux-musleabihf]
linker = "arm-linux-musleabihf-gcc"

[alias]
build-opi = "build --target armv7-unknown-linux-gnueabihf --release"
build-opi-musl = "build --target armv7-unknown-linux-musleabihf --release"