//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.1

pub use super::admin_mac::Entity as AdminMac;
pub use super::client::Entity as Client;
pub use super::data_plan::Entity as DataPlan;
pub use super::plan::Entity as Plan;
pub use super::redeemable_code::Entity as RedeemableCode;
